SET IDENTITY_INSERT [dbo].[Monsters] ON
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (1, N'Gobbo', 30, N'Goblin', 7, 5, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (2, N'Trolly', 80, N'Troll', NULL, NULL, 10, 1)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (3, N'Bobbo', 30, N'Goblin', 3, 8, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (4, N'Sniv', 25, N'Goblin', 5, 6, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (5, N'Runt', 20, N'Goblin', 2, 4, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (6, N'Spike', 35, N'Goblin', 10, 9, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (7, N'Grizzle', 40, N'Goblin', 15, 12, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (8, N'Fizz', 22, N'Goblin', 1, 7, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (9, N'Munch', 28, N'Goblin', 6, 5, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (10, N'Knik', 18, N'Goblin', 3, 4, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (11, N'Sly', 27, N'Goblin', 8, 6, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (12, N'Pipsqueak', 16, N'Goblin', 1, 3, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (13, N'Gnasher', 33, N'Goblin', 12, 11, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (14, N'Murk', 30, N'Goblin', 9, 8, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (15, N'Twitch', 24, N'Goblin', 4, 6, NULL, NULL)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (16, N'Rockjaw', 95, N'Troll', NULL, NULL, 18, 1)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (17, N'Bridgekeeper', 110, N'Troll', NULL, NULL, 20, 1)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (18, N'Mould', 70, N'Troll', NULL, NULL, 12, 0)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (19, N'Thud', 85, N'Troll', NULL, NULL, 14, 0)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (20, N'Bramble', 60, N'Troll', NULL, NULL, 10, 0)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (21, N'Deepmaw', 120, N'Troll', NULL, NULL, 22, 1)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (22, N'Stonegut', 75, N'Troll', NULL, NULL, 13, 0)
INSERT INTO [dbo].[Monsters] ([Id], [Name], [HitPoints], [MonsterType], [Gold], [Attack], [Defense], [Regenerate]) VALUES (23, N'Gronk', 100, N'Troll', NULL, NULL, 17, 1)
SET IDENTITY_INSERT [dbo].[Monsters] OFF